from .utils import get_record_metadata
from .Constants.Constants import CHECKBOX, BLANK_CHECKBOX


def generate_restricted_controlled_materials_list_md(request, html_file, material_types_dict=None, material_types=None):
    html_file.write("# Controlled Materials")
    html_file.write("\n")

    if "response" in request and "materials" in request["response"]:
        # Write html file header
        html_file.write("<html>")
        html_file.write("<head>")
        html_file.write("<meta charset=\"utf-8\">")
        html_file.write("<link href=\"report.css\" rel=\"stylesheet\">")
        html_file.write("<title>Report</title>")
        html_file.write("<meta name=\"description\" content=\"Report example\">")
        html_file.write("</head>")
        html_file.write("<body>")
        # write table of contents
        html_file.write("<article id=\"contents\">")
        html_file.write("<h2>Table of contents</h2>")
        html_file.write("<ul>")
        for mt in material_types:
            html_file.write("<li><a href=\"#{}-title\"></a></li>".format(mt))
        html_file.write("</ul>")
        html_file.write("</article>")

        for material in  request["response"]["materials"]:
            name = material["nurims.title"]
            withdrawn = material["nurims.withdrawn"]
            gender = get_record_metadata(material, "nurims.entity.sex", "&nbsp;")
            iswholebodymonitored = True if get_record_metadata(material, "nurims.entity.iswholebodymonitored", "false") == "true" else False
            isextremitymonitored = True if get_record_metadata(material, "nurims.entity.isextremitymonitored", "false") == "true" else False
            iswristmonitored = True if get_record_metadata(material, "nurims.entity.iswristmonitored", "false") == "true" else False
            dob = get_record_metadata(material, "nurims.entity.dob", "&nbsp;")
            nid = get_record_metadata(material, "nurims.entity.nid", "&nbsp;")
            work_details = get_record_metadata(material, "nurims.entity.workdetails", "&nbsp;")
            contact = get_record_metadata(material, "nurims.entity.contact", "&nbsp;")
            address = get_record_metadata(material, "nurims.entity.address", "&nbsp;")
            avatar = get_record_metadata(material, "nurims.entity.avatar", "&nbsp;")
            html_file.write("<table style=\"width:100%\">")
            # html_file.write("<thead>")
            # html_file.write("<tr>")
            # html_file.write("<th>&nbsp;</th>")
            # html_file.write("<th>&nbsp;</th>")
            # html_file.write("<th style=\"text-align:center\">Whole Body <br/> Monitoring</th>")
            # html_file.write("<th style=\"text-align:center\">Ring <br/> Monitoring</th>")
            # html_file.write("<th style=\"text-align:center\">Wrist <br/> Monitoring</th>")
            # html_file.write("</tr>")
            # html_file.write("</thead>")
            html_file.write("<tbody>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> <h2>&nbsp; Details</h2> </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td>&nbsp;</td>")
            html_file.write("<td>&nbsp;</td>")
            html_file.write("<td style=\"text-align:center\">Whole Body <br/> Monitoring</td>")
            html_file.write("<td style=\"text-align:center\">Ring <br/> Monitoring</td>")
            html_file.write("<td style=\"text-align:center\">Wrist <br/> Monitoring</td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top; width:20%\">Name: </td>")
            html_file.write("<td style=\"text-align:left; vertical-align:top; width:50%\"> {} </td>".format(name))

            html_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if iswholebodymonitored else BLANK_CHECKBOX))
            html_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if isextremitymonitored else BLANK_CHECKBOX))
            html_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if iswristmonitored else BLANK_CHECKBOX))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> Status: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format("INACTIVE" if withdrawn == 1 else "ACTIVE"))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> Gender: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format("Male" if gender == "m" else "Female" if gender == "f" else gender))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> Date Of Birth: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format(dob))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> National ID: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format(nid))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Address: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"><code>{}</code></td>".format(address))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Work: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"><code>{}</code></td>".format(work_details))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Contact: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\">{}</td>".format(contact))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Avatar: </td>")
            html_file.write("<td style=\"text-align:left; vertical-align:top;\" colspan=\"4\"><img src=\"{}\" style=\"width:128px;\"/></td>".format(avatar))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> &nbsp; </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> <h2>&nbsp; Roles</h2> </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> &nbsp; </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> <h2>&nbsp; Training Programmes</h2> </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> &nbsp; </td>")
            html_file.write("</tr>")
            html_file.write("</tbody>")
            html_file.write("</table>")
            html_file.write("<br/>")
            html_file.write("<div style=\"page-break-after: always;\"></div>")


def generate_unrestricted_controlled_materials_list_md(request, html_file):
    html_file.write("# Controlled Materials")
    html_file.write("\n")

    if "response" in request and "materials" in request["response"]:
        access = request["access"] if "access" in request else "restricted"
        for material in  request["response"]["materials"]:
            name = material["nurims.title"]
            withdrawn = material["nurims.withdrawn"]
            gender = get_record_metadata(material, "nurims.entity.sex", "&nbsp;")
            iswholebodymonitored = True if get_record_metadata(material, "nurims.entity.iswholebodymonitored", "false") == "true" else False
            isextremitymonitored = True if get_record_metadata(material, "nurims.entity.isextremitymonitored", "false") == "true" else False
            iswristmonitored = True if get_record_metadata(material, "nurims.entity.iswristmonitored", "false") == "true" else False
            dob = get_record_metadata(material, "nurims.entity.dob", "&nbsp;")
            nid = get_record_metadata(material, "nurims.entity.nid", "&nbsp;")
            work_details = get_record_metadata(material, "nurims.entity.workdetails", "&nbsp;")
            contact = get_record_metadata(material, "nurims.entity.contact", "&nbsp;")
            address = get_record_metadata(material, "nurims.entity.address", "&nbsp;")
            avatar = get_record_metadata(material, "nurims.entity.avatar", "&nbsp;")
            html_file.write("<table style=\"width:100%\">")
            # html_file.write("<thead>")
            # html_file.write("<tr>")
            # html_file.write("<th>&nbsp;</th>")
            # html_file.write("<th>&nbsp;</th>")
            # html_file.write("<th style=\"text-align:center\">Whole Body <br/> Monitoring</th>")
            # html_file.write("<th style=\"text-align:center\">Ring <br/> Monitoring</th>")
            # html_file.write("<th style=\"text-align:center\">Wrist <br/> Monitoring</th>")
            # html_file.write("</tr>")
            # html_file.write("</thead>")
            html_file.write("<tbody>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> <h2>&nbsp; Details</h2> </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td>&nbsp;</td>")
            html_file.write("<td>&nbsp;</td>")
            html_file.write("<td style=\"text-align:center\">Whole Body <br/> Monitoring</td>")
            html_file.write("<td style=\"text-align:center\">Ring <br/> Monitoring</td>")
            html_file.write("<td style=\"text-align:center\">Wrist <br/> Monitoring</td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top; width:20%\">Name: </td>")
            html_file.write("<td style=\"text-align:left; vertical-align:top; width:50%\"> {} </td>".format(name))

            html_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if iswholebodymonitored else BLANK_CHECKBOX))
            html_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if isextremitymonitored else BLANK_CHECKBOX))
            html_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if iswristmonitored else BLANK_CHECKBOX))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> Status: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format("INACTIVE" if withdrawn == 1 else "ACTIVE"))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> Gender: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format("Male" if gender == "m" else "Female" if gender == "f" else gender))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> Date Of Birth: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format(dob))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right;\"> National ID: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format(nid))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Address: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"><code>{}</code></td>".format(address))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Work: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\"><code>{}</code></td>".format(work_details))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Contact: </td>")
            html_file.write("<td style=\"text-align:left;\" colspan=\"4\">{}</td>".format(contact))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td style=\"text-align:right; vertical-align:top;\"> Avatar: </td>")
            html_file.write("<td style=\"text-align:left; vertical-align:top;\" colspan=\"4\"><img src=\"{}\" style=\"width:128px;\"/></td>".format(avatar))
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> &nbsp; </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> <h2>&nbsp; Roles</h2> </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> &nbsp; </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> <h2>&nbsp; Training Programmes</h2> </td>")
            html_file.write("</tr>")
            html_file.write("<tr>")
            html_file.write("<td colspan=\"5\"> &nbsp; </td>")
            html_file.write("</tr>")
            html_file.write("</tbody>")
            html_file.write("</table>")
            html_file.write("<br/>")
            html_file.write("<div style=\"page-break-after: always;\"></div>")

