from .utils import get_record_metadata
from .Constants.Constants import CHECKBOX, BLANK_CHECKBOX

def generate_personnel_records_md(request, md_file):
    md_file.write("# Personnel List")

    if "response" in request and "personnel" in request["response"]:
        for person in  request["response"]["personnel"]:
            name = person["nurims.title"]
            withdrawn = person["nurims.withdrawn"]
            gender = get_record_metadata(person, "nurims.entity.sex", "&nbsp;")
            iswholebodymonitored = True if get_record_metadata(person, "nurims.entity.iswholebodymonitored", "false") == "true" else False
            isextremitymonitored = True if get_record_metadata(person, "nurims.entity.isextremitymonitored", "false") == "true" else False
            iswristmonitored = True if get_record_metadata(person, "nurims.entity.iswristmonitored", "false") == "true" else False
            dob = get_record_metadata(person, "nurims.entity.dob", "&nbsp;")
            nid = get_record_metadata(person, "nurims.entity.nid", "&nbsp;")
            work_details = get_record_metadata(person, "nurims.entity.workdetails", "&nbsp;")
            contact = get_record_metadata(person, "nurims.entity.contact", "&nbsp;")
            address = get_record_metadata(person, "nurims.entity.address", "&nbsp;")
            avatar = get_record_metadata(person, "nurims.entity.avatar", "&nbsp;")
            md_file.write("<table style=\"width:100%\">")
            # md_file.write("<thead>")
            # md_file.write("<tr>")
            # md_file.write("<th>&nbsp;</th>")
            # md_file.write("<th>&nbsp;</th>")
            # md_file.write("<th style=\"text-align:center\">Whole Body <br/> Monitoring</th>")
            # md_file.write("<th style=\"text-align:center\">Ring <br/> Monitoring</th>")
            # md_file.write("<th style=\"text-align:center\">Wrist <br/> Monitoring</th>")
            # md_file.write("</tr>")
            # md_file.write("</thead>")
            md_file.write("<tbody>")
            md_file.write("<tr>")
            md_file.write("<td colspan=\"5\"> <h2>&nbsp; Details</h2> </td>")
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td>&nbsp;</td>")
            md_file.write("<td>&nbsp;</td>")
            md_file.write("<td style=\"text-align:center\">Whole Body <br/> Monitoring</td>")
            md_file.write("<td style=\"text-align:center\">Ring <br/> Monitoring</td>")
            md_file.write("<td style=\"text-align:center\">Wrist <br/> Monitoring</td>")
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right; vertical-align:top; width:20%\">Name: </td>")
            md_file.write("<td style=\"text-align:left; vertical-align:top; width:50%\"> {} </td>".format(name))

            md_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if iswholebodymonitored else BLANK_CHECKBOX))
            md_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if isextremitymonitored else BLANK_CHECKBOX))
            md_file.write("<td style=\"text-align:center; vertical-align:top; width:10%\"><h2>{}</h2></td>".format(CHECKBOX if iswristmonitored else BLANK_CHECKBOX))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right;\"> Status: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format("INACTIVE" if withdrawn == 1 else "ACTIVE"))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right;\"> Gender: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format("Male" if gender == "m" else "Female" if gender == "f" else gender))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right;\"> Date Of Birth: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format(dob))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right;\"> National ID: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\"> {} </td>".format(nid))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right; vertical-align:top;\"> Address: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\"><code>{}</code></td>".format(address))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right; vertical-align:top;\"> Work: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\"><code>{}</code></td>".format(work_details))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right; vertical-align:top;\"> Contact: </td>")
            md_file.write("<td style=\"text-align:left;\" colspan=\"4\">{}</td>".format(contact))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td style=\"text-align:right; vertical-align:top;\"> Avatar: </td>")
            md_file.write("<td style=\"text-align:left; vertical-align:top;\" colspan=\"4\"><img src=\"{}\" style=\"width:128px;\"/></td>".format(avatar))
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td colspan=\"5\"> &nbsp; </td>")
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td colspan=\"5\"> <h2>&nbsp; Roles</h2> </td>")
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td colspan=\"5\"> &nbsp; </td>")
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td colspan=\"5\"> <h2>&nbsp; Training Programmes</h2> </td>")
            md_file.write("</tr>")
            md_file.write("<tr>")
            md_file.write("<td colspan=\"5\"> &nbsp; </td>")
            md_file.write("</tr>")
            md_file.write("</tbody>")
            md_file.write("</table>")
            md_file.write("<br/>")
            md_file.write("<div style=\"page-break-after: always;\"></div>")
